version: 1.0.{build}
image: Visual Studio 2017
services:
  - mssql2016
  - mongodb
shallow_clone: true
build_script:
- ps: >- 

    $env:NSTORE_LOG_POLLER = "none";    
    
    $env:NSTORE_LOG_LEVEL = "none";

    .\build.ps1 -ScriptArgs '-NSTORE_MSSQL_INSTANCE="Server=(local)\SQL2016,1433;User ID=sa;Password=Password12!;"'

test: off
cache:
  - C:\Users\appveyor\AppData\Local\NuGet -> appveyor.yml

